CREATE DATABASE gst WITH ENCODING='UTF8' LC_CTYPE='en_US.UTF-8' LC_COLLATE='en_US.UTF-8' OWNER=vagrant TEMPLATE=template0 CONNECTION LIMIT=-1;
ALTER DATABASE gst SET bytea_output = 'escape';
GRANT ALL PRIVILEGES ON DATABASE gst to vagrant;
